### PR TITLE
Implement tslint

### LINKED ISSUE #113: implement TsLint in travis to ensure code quality
Implement TsLint task in gulp to validate code quality issues on Javascript side

### PR DESCRIPTION
**Pull request by ankit213**
Fixes #113 

Changed Files:
gulpfile.js : added new task for tslint
package.json: added new packages for tslint
tslint.json : added tslint.json to define rules.
travis.yml : added command to run 'tslint'

### CODE REVIEW

**Comment by chintans** [comment]
How will tslint run in travis?

**Comment by ankit213** [comment]
i didn't added coomand in travis i juts add gulp task ,if you run in travis so addded command in travis.yml

**Comment by chintans** [comment]
@ankit213 I think it is clearly mentioned in an issue that it needs to run in Travis. Why have you submitted pull request without it? Also, your comment is wrong English.

**Comment by chintans** [comment]
Please rebase your branch too. it is outdated

**Comment by ankit213** [comment]
Actually,  I read description part that i:e. "Implement TsLint task in gulp to validate code quality issues on Javascript side" so I got confused about this.

**Comment by ankit213** [comment]
if you want command so i will be added

**Comment by ankit213** [comment]
i have added command in trvais.yml for tslint

**Comment by chintans** [comment]
close #113

**Pull request merged**
